### ISSUE TITLE
extradata mounts from same PVC fail

### ISSUE THREAD

**Issue by ohthehugemanatee** [ressu/kube-plex#15]
Right now each mount assumes it's the only one using that PVC. In my case, I have a PVC for my NFS filesystem. `plex` and `movies` directories are peers at the top level, so I have to mount in `data` and `extradata-movies` separately:

```
  data:
    claimName: "nfs-claim"
    subPath: "plex"
    storageClass: ""
  extraData:
    - name: "media"
      claimName: "nfs-claim"
      subPath: "media"
      storageClass: ""
```

The helm chart creates a deployment with two identical Volumes for `nfs-claim`, which fails. Instead, we should notice that the same claimName is specified, and only create one PV. You could maybe do this by naming the Volume after the PVC....
