### ISSUE TITLE
Plex Transcoder fails with Protected process returned an error

### ISSUE THREAD

**Issue by rkbennett** [ressu/kube-plex#43]
Kubernetes:
v1.27.2
plex version:
plexinc/pms-docker:1.32.3.7192-7aa441827

When attempting to stream a movie, plex fails with "Protected process returned an error: exit status 1"

This is the only log generated that I can see related to kube-plex. Even attempting to manually execute the binary from inside the container results in this error with no other output. I've tried both the ghcr.io/ressu/kube-plex:latest, and building this repo's main branch and both result in the same error.

I am using SMB-based PVCs for config, data, and transcode. Though I'm not sure that's really relevant sense it's not even getting that far.

I forgot to add that no jobs or transcode pods are ever generated.

**Comment by ressu** [comment]
Could you include your configuration here, that'll make it easier to understand what could be happening. Feel free to remove any passwords and change addresses if there are any in your configuration.

**Comment by rkbennett** [comment]
You're talking about the kubernetes manifests?

**Comment by ressu** [comment]
Depending on the way how you configured your kube-plex, the manifests or the helm configuration. Either one works.

**Comment by rkbennett** [comment]
```
---
# Source: kube-plex/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plex
  namespace: plex
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: plex-smb
provisioner: smb.csi.k8s.io
parameters:
  source: "//nas/plex-content"
  csi.storage.k8s.io/provisioner-secret-name: "smbcreds"
  csi.storage.k8s.io/provisioner-secret-namespace: "kube-system"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "kube-system"
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0555
  - file_mode=0444
  - uid=0
  - gid=0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-smb
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: plex-smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: "nas/plex-content"
    volumeAttributes:
      source: "//nas/plex-content"
    nodeStageSecretRef:
      name: "smbcreds"
      namespace: kube-system
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-smb-config
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: common-smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: "nams/k8s/plex"
    volumeAttributes:
      source: "//nas/k8s"
      subDir: plex
    nodeStageSecretRef:
      name: "smbcreds"
      namespace: kube-system
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-transcode
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: common-smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: "nas/k8s/transcode"
    volumeAttributes:
      source: "//nas/k8s"
      subDir: plex
    nodeStageSecretRef:
      name: "smbcreds"
      namespace: kube-system
---
# Source: kube-plex/templates/volumes.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-smb
  namespace: plex
  labels:
    app: kube-plex
spec:
  accessModes:
  - "ReadOnlyMany"
  resources:
    requests:
      storage: "20Gi"
  volumeName: plex-smb
  storageClassName: plex-smb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-smb-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: plex-smb-config
  storageClassName: common-smb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-transcode
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: plex-transcode
  storageClassName: common-smb
---
# Source: kube-plex/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: plex
  namespace: plex
  labels:
    app: kube-plex
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
# Source: kube-plex/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: plex
  namespace: plex
  labels:
    app: kube-plex
    chart: kube-plex-0.2.7
    release: plex
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: plex
subjects:
- kind: ServiceAccount
  name: plex
  namespace: "plex"
---
# Source: kube-plex/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: plex
  labels:
    app: kube-plex
spec:
  type: ClusterIP
  ports:
    - name: pms
      port: 80
      protocol: TCP
      targetPort: 32400
    - name: pms-internal
      port: 32400
      protocol: TCP
      targetPort: 32400
    - name: https
      port: 443
      targetPort: 32443
  selector:
    app: kube-plex
---
# Source: kube-plex/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: plex
  labels:
    app: kube-plex
  annotations:
    cert-manager.io/issuer: common-issuer
    cert-manager.io/issuer-kind: ClusterIssuer
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: '36000'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '1800'
    nginx.ingress.kubernetes.io/proxy_http_version: '1.1'
    nginx.ingress.kubernetes.io/proxy_set_header: Upgrade
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: plex.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex
                port:
                  number: 32400
  tls:
  - hosts:
    - plex.local
    secretName: tls-plex-ingress
---
# Source: kube-plex/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: plex
  labels:
    app: kube-plex
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kube-plex
  template:
    metadata:
      labels:
        app: kube-plex
      annotations:
        kube-plex/container-name: "kube-plex-init"
        kube-plex/pms-addr: plex:32400
        kube-plex/pms-container-name: "plex"
    spec:
      serviceAccountName: plex
      hostname: "plex"
      hostNetwork: true
      initContainers:
      - name: kube-plex-install
        image: "ghcr.io/ressu/kube-plex:latest"
        imagePullPolicy: Always
        command:
        - cp
        - /kube-plex
        - /shared/kube-plex
        volumeMounts:
        - name: shared
          mountPath: /shared
      containers:
      - name: plex
        image: "plexinc/pms-docker:1.32.3.7192-7aa441827"
        imagePullPolicy: IfNotPresent
        # We replace the PMS binary with a postStart hook to save having to
        # modify the default image entrypoint.
        lifecycle:
          postStart:
            exec:
              command:
              - bash
              - -c
              - |
                #!/bin/bash
                set -e
                mv '/usr/lib/plexmediaserver/Plex Transcoder' '/usr/lib/plexmediaserver/Plex Transcoder.orig'
                cp /shared/kube-plex '/usr/lib/plexmediaserver/Plex Transcoder'
        livenessProbe:
          tcpSocket:
            port: 32400
          initialDelaySeconds: 0
          failureThreshold: 3
          timeoutSeconds: 1
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 32400
          initialDelaySeconds: 0
          failureThreshold: 3
          timeoutSeconds: 1
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: 32400
          initialDelaySeconds: 0
          failureThreshold: 30
          timeoutSeconds: 1
          periodSeconds: 5
        env:
        - name: TZ
          value: "Etc/UTC"
        # TODO: move this to a secret?
        - name: PLEX_CLAIM
          valueFrom:
            secretKeyRef:
              name: plex-claim
              key: claim
        # kube-plex env vars
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ADVERTISE_IP
          value: |
            https://plex.local:443
            ,https://plex.local
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /config
        - name: transcode
          mountPath: /transcode
        - name: shared
          mountPath: /shared
        resources:
          {}
      nodeSelector:
        kubernetes.io/arch: amd64
        compatibility: plex
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: "plex-smb"
      - name: config
        persistentVolumeClaim:
          claimName: "plex-smb-config"
      - name: transcode
        persistentVolumeClaim:
          claimName: "plex-transcode"
      - name: shared
        emptyDir: {}
---
###Add Secret!!!
###
###kubectl create secret generic plex-claim --from-literal=claim="<Insert Secret Here>" -n plex
```
